AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3
  Exclude:
    - vendor/**/*
    - spec/**/*

Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false
Style/MapIntoArray:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SuperArguments:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Max: 27
Metrics/ClassLength:
  CountComments: false
  Max: 200
Metrics/MethodLength:
  CountComments: false
  Max: 25

Naming/PredicateMethod:
  Enabled: false

# Metrics/MethodLength:
#   CountComments: false
#   Max: 25
# Metrics/ModuleLength:
#   CountComments: false
#   Max: 200
# Metrics/CyclomaticComplexity:
#   Max: 7

# Documentation:
#   Enabled: false

# AllCops:
#   TargetRubyVersion: 2.7
#   Exclude:
#     - bin/**/*
#     - vendor/**/*
#     - tmp/**/*
#     - spec/**/*
