steps:
  - label: ":rspec: Run rspec"
    command:
      - "bundle install"
      - "bundle exec rspec"
    plugins:
      - docker#v3.3.0:
          image: ruby:3.3

  - label: ":rubocop: Run the cop"
    command:
      - "bundle install"
      - "echo 'running rubocop'"
      - "bundle exec rubocop"
    plugins:
      - docker#v3.3.0:
          image: ruby:3.3
  - wait

  - label: ":pick:  Build and Push"
    command:
      - "bundle install"
      - "gem build && gem push *.gem"
    branches: master
    plugins:
      - docker#v3.3.0:
          image: ruby:3.3
          environment:
            - GEM_HOST_API_KEY
            - GIT_AUTHOR_NAME=Fat Zebra
            - GIT_AUTHOR_EMAIL=support@fatzebra.com
    agents:
      queue: aws
      Environment: test
